In [2]:
import  torch
import pandas as pd
import numpy as np

# Fundamentals

In [3]:
# Basics in tensors

tensor_1 = torch.tensor(np.array([[7,8,9],[4,3,6]]),dtype = torch.float32)
tensor_2 = tensor_1.clone()
#tensor_3 = tensor_2
print(tensor_1.size())
print(tensor_2)

#changing one entry
tensor_1[1][2] = 0
#clone will create a new tensor but detach() disconnects the current tensor from the computation graph
#detach uses less memory since it won't calculate gradients
print(tensor_1)
print(tensor_2)

torch.Size([2, 3])
tensor([[7., 8., 9.],
        [4., 3., 6.]])
tensor([[7., 8., 9.],
        [4., 3., 0.]])
tensor([[7., 8., 9.],
        [4., 3., 6.]])


In [4]:
tensor_1.ndim

2

In [5]:
tensor_1.shape

torch.Size([2, 3])

In [6]:
multi_tensor = torch.tensor([[[[1,2,3],
                              [3,2,3],
                              [4,2,2]]]])

In [7]:
multi_tensor.ndim # '['

4

In [8]:
multi_tensor.shape

torch.Size([1, 1, 3, 3])

In [9]:
multi_tensor[0][0][1][1]

tensor(2)

In [10]:
#Random tensors
random_tensor = torch.rand(1,2,3)
random_tensor

tensor([[[0.3184, 0.1701, 0.4334],
         [0.2671, 0.0141, 0.1578]]])

In [11]:
image_tensor = torch.rand(size=(3,224,224))

In [12]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
#Similar to java, it does the auto conversion to the larger data type
t1 = torch.tensor([1.888,2,3],dtype = torch.float16)
t2 = torch.tensor([2.0,3,6],dtype = torch.float32)
t = t1*t2
t.dtype

torch.float32

In [14]:
tensor_x = torch.arange(10,1000,step = 20,dtype = torch.float32)
torch.mean(tensor_x),torch.argmax(tensor_x), tensor_x.shape

(tensor(500.), tensor(49), torch.Size([50]))

In [15]:
## reshaping, squeezing
## view --> different representation but shares same memory space 
## squeeze - removes all 1-dimensional tensor
## unsqueeze(dim*) - adds an extra dimension in *row(dim=0) and column(dim=1)
## stack - dim=0 (row) and dim=1 (column)
## permute - swaps/shifts the tensor dimensions

tensor_x.reshape(5,10) 

tensor([[ 10.,  30.,  50.,  70.,  90., 110., 130., 150., 170., 190.],
        [210., 230., 250., 270., 290., 310., 330., 350., 370., 390.],
        [410., 430., 450., 470., 490., 510., 530., 550., 570., 590.],
        [610., 630., 650., 670., 690., 710., 730., 750., 770., 790.],
        [810., 830., 850., 870., 890., 910., 930., 950., 970., 990.]])

In [16]:
new_tensor = tensor_x.view(1,50)
new_tensor

tensor([[ 10.,  30.,  50.,  70.,  90., 110., 130., 150., 170., 190., 210., 230.,
         250., 270., 290., 310., 330., 350., 370., 390., 410., 430., 450., 470.,
         490., 510., 530., 550., 570., 590., 610., 630., 650., 670., 690., 710.,
         730., 750., 770., 790., 810., 830., 850., 870., 890., 910., 930., 950.,
         970., 990.]])

In [17]:
squeezed_tensor = new_tensor.squeeze()
squeezed_tensor.shape

torch.Size([50])

In [18]:
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=0)
unsqueezed_tensor, unsqueezed_tensor.shape

(tensor([[ 10.,  30.,  50.,  70.,  90., 110., 130., 150., 170., 190., 210., 230.,
          250., 270., 290., 310., 330., 350., 370., 390., 410., 430., 450., 470.,
          490., 510., 530., 550., 570., 590., 610., 630., 650., 670., 690., 710.,
          730., 750., 770., 790., 810., 830., 850., 870., 890., 910., 930., 950.,
          970., 990.]]), torch.Size([1, 50]))

In [19]:
x = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
x[:,1,2]

tensor([6])

In [20]:
#numpy array to tensors
numpy_array = np.array(([7,4,1],
                        [2,5,8],
                        [9,6,3]))
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor.dtype)
#numpy array >> default dtype: int64 thus from_numpy creates float64 tensors by default (pytorch default: float32)

#safe usage
pytorch_tensor = torch.from_numpy(numpy_array).type(torch.float32)
print(f'pytorch_tensor: {pytorch_tensor}')

##tensor to numpy array
#tensor_ = torch.tensor(([1,1,1],
#                       [4,4,4]))
numpy_ = pytorch_tensor.numpy()
print(f'numpy array: {numpy_}')

torch.int64
pytorch_tensor: tensor([[7., 4., 1.],
        [2., 5., 8.],
        [9., 6., 3.]])
numpy array: [[7. 4. 1.]
 [2. 5. 8.]
 [9. 6. 3.]]


In [21]:
#random seed (just a usage example)
torch.manual_seed(42)
rand_1 = torch.rand(2,2)
rand_1

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])

In [25]:
### Accessing GPUs
torch.cuda.is_available()

#usage
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [35]:
#moving tensors
rand_1 = rand_1.to(device)
rand_1

#numpy operations won't be running on GPÜs
array = rand_1.cpu().numpy()
array

array([[0.88226926, 0.91500396],
       [0.38286376, 0.95930564]], dtype=float32)