# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
import torch
import numpy as np

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Create random tensor
random_tensor = torch.rand(size = (7,7), dtype = torch.float32)
random_tensor

tensor([[0.2143, 0.6489, 0.2628, 0.2363, 0.6763, 0.4810, 0.7630],
        [0.3123, 0.0300, 0.3636, 0.6602, 0.5497, 0.9938, 0.6341],
        [0.8435, 0.4594, 0.8694, 0.0799, 0.0945, 0.0104, 0.9208],
        [0.9414, 0.9208, 0.7062, 0.3943, 0.1405, 0.5505, 0.9308],
        [0.6852, 0.5238, 0.8668, 0.4060, 0.7820, 0.8200, 0.4807],
        [0.8554, 0.9199, 0.0095, 0.3622, 0.9906, 0.2681, 0.8328],
        [0.0584, 0.1611, 0.1390, 0.8452, 0.6556, 0.4063, 0.8678]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor_1 = torch.rand(size=(1,7), dtype = torch.float32)
#random_tensor_1 = torch.transpose(random_tensor_1,0,1)
transposed_random_tensor_1 = torch.t(random_tensor_1)

# Perform matrix multiplication 
tensor_product = torch.matmul(random_tensor, transposed_random_tensor_1)
print(f'tensor_product: {tensor_product}')


tensor_product: tensor([[1.0185],
        [1.1335],
        [0.7380],
        [1.2373],
        [1.5074],
        [1.5531],
        [0.9026]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_1 = torch.rand(size = (7,7))
tensor_2 = torch.rand(size = (1,7))

# Matrix multiply tensors
print(f'{torch.matmul(tensor_1, tensor_2.T)}')

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Create two random tensors on GPU
#rand_tensor_1 = torch.rand(size = (2,3), device = device) #same but the tensor generated is different, why?
rand_tensor_1 = torch.rand(size = (2,3)).to(device)
rand_tensor_2 = torch.rand(size = (2,3)).to(device)

rand_tensor_1, rand_tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
tranposed_rand_tensor_2 = rand_tensor_2.T
product_ = torch.matmul(rand_tensor_1, tranposed_rand_tensor_2)
print(f'{product_}')

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max = torch.max(product_)
# Find min
min = torch.min(product_)

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
max_index = torch.argmax(product_)
# Find arg min
min_index = torch.argmin(product_)

max_index, min_index #output: think of flattened tensor

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
multi_tensor_1 = torch.rand(size = (1,1,1,10), dtype = torch.float32)

# Remove single dimensions
squeezed_multi_tensor_1 = multi_tensor_1.squeeze()

# Print out tensors and their shapes
multi_tensor_1, squeezed_multi_tensor_1, squeezed_multi_tensor_1.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))